# For more info on HTTP files go to https://aka.ms/vs/httpfile
@schema=https
@hostname=localhost
@port=7115

GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities

###
GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities
Accept:application/xml

###
POST {{schema}}://{{hostname}}:{{port}}/api/v2/cities
Accept: application/xml 
Content-Type: application/json

{
  "name": "A name for testing",
  "description": "A description for testing"
} 

###

@poiid = {{createpoi.response.body.id}}

POST {{schema}}://{{hostname}}:{{port}}/api/v2/cities
Accept: application/xml 
Content-Type: application/json

{
  "name": "A name for testing",
  "description": "A description for testing"
} 

###

POST {{schema}}://{{hostname}}:{{port}}/api/authentication/authenticate
Content-Type: application/json

{
    "username": "KevinDockx",
    "password": "This is a relatively long sentence that acts as my password"
}

###

GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IktldmluIiwiZmFtaWx5X25hbWUiOiJEb2NreCIsImNpdHkiOiJBbnR3ZXJwIiwibmJmIjoxNzA1NTc0Mjg0LCJleHAiOjE3MDU1Nzc4ODQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcxNjkiLCJhdWQiOiJjaXR5aW5mb2FwaSJ9.H7mXjRGrVSyvpQ9JczohPb-nagVVknDTEhM4fp8wq3g
